/* cSpell:disable-next-line */
export const LONG_EXPIRY_JWT_TOKEN = "eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE5MTU4NjQ4MDgsImlhdCI6MTY2MzQ5MDQwOCwidXNlcm5hbWUiOiJyZWFjdC1zc3IifQ.vI_bBNvpUZpcgFpz6dcbHnXxQwvLhxB-lRNzuoRC3Qw";
/* cSpell:disable-next-line */
export const EXPIRED_JWT_TOKEN = "eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjM0MDQwMDgsInVzZXIiOiJyZWFjdC1zc3IiLCJpYXQiOjE2NjM0OTA0MDh9.B02YyTsPhsIDwQi_OCKejMwgfMQkzrFB7hZ3_WU0Pcg";