name: Build & Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Run test with Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      # - name: Cypress.io
      #   uses: cypress-io/github-action@v4.2.0
      #   with:
      #     install: npm ci
      #     start: npm run start:cypress:ci
      #     build: npm run build:cypress
      #     wait-on: http://localhost:5000
      #     command: npm test
      # - name: Codecov upload coverage
      #   uses: codecov/codecov-action@v3.1.1
      #   with:
      #     name: Cypress with Jest Coverage
      - name: Lighthouse Score
        run: node lighthouse/lighthouse-score.js

      - name: Commit Lighthouse score
        uses: stefanzweifel/git-auto-commit-action@v4.15.0
        with:
          commit_message: Lighthouse score badge auto commit
          branch: main
          commit_options: "--no-verify --signoff"
          token: ${{ secrets.PAT }}
          push_options: --force
