name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Run test with Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Cypress.io
        uses: cypress-io/github-action@v4.2.0
        with:
          install: npm ci
          start: npm run start:cypress:ci
          build: npm run build:cypress
          wait-on: http://localhost:5000
          command: npm test
      - name: Codecov upload coverage
        uses: codecov/codecov-action@v3.1.1
        with:
          name: Cypress with Jest Coverage
